language: java

jdk:
  - openjdk17

dist: trusty

cache:
  directories:
    - $HOME/.m2

stages:
  - test
  - name: deploy-snapshots
    if: branch = master AND type = push
  - name: release-check
    if: (branch =~ /^release.*/)
  - name: release
    if: (branch =~ /^release.*/)

before_install:
  # Ensure the settings we want to use are in place before running the default mvn install
  - cp ./travis/maven-settings.xml $HOME/.m2/settings.xml
  - sed -i "s/-SNAPSHOT/-build-$TRAVIS_BUILD_NUMBER/" pom.xml

jobs:
  include:
    - stage: test
      addons:
        sonarcloud:
          organization: "susom"
          token:
            secure: "fKkTA+6hW7dLjQPk6xfJWqyk57r0Z4c5vDWCfGXgP8dqWbo6tXFSb/GIJ34gf9kfOzFfRYpoNySBI38cTp3tjc4WX5A13DwMdHv7xGQucBMkioSeO3POM3koaAxm5XT4V7Z+fVInAbZrwqc4xsWKThPRZPJtKx/KKggzviZRds6fWlI9LwGXk4bz7Mj9cP8Aj+a14GClevVm+WSgx9zrcJ52I93tQLnyLVz0fiO8z8WVM4H0HKgxQFiDlI93AMD22li7V9Z2mWZOA4/ZzeAuyQrajsSlWmDo/g31uiLZmBsNz/U4JXLjxdmgvCU8wNFo7bvkwB0OV1bSuT6f5BOJeFA0paOIiVftBopME6E0O7i3vzW3TOgnCCBqBPcI6+CAw9Am0aRGYeXCXdZw4BgqLwxzIc8XN5NfPK8terVXUIfNd1YrpjmGktWGOYF2mXNf3tpjKy8RRZaZ6UPx/2USmLEleUW/qAGA4nepz7nzP5lv/yN1Kg++cDT43hrzvp/4+/2ALUlkbcsRBi0ldy22ngfHmpdTC84S5WJb+v0JGI6lO2lYWvsXkm+m39W57+3xRXnvHjIBsdTLn7rD8C8ewmBqgEyAufcdx5nJSy0bvjpcECjdFSGi89t3mAgyuWtLUreBWqqMH+NxcwnOHwo9sxa6R0uab4SJA8kuNJEiino="
      # Skip the default mvn command because we want to set the profile explicitly
      install: true
      script:
        - echo "test"
        - mvn -Dmaven.wagon.http.retryHandler.count=3 -e -Pcoverage org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.projectKey=susom_vertx-base verify
      after_failure:
        - echo "\n=== SUREFIRE REPORTS ===\n"
        - for F in target/surefire-reports/*.txt; do echo $F; cat $F; echo; done
    - stage: deploy-snapshots
      script:
        - echo "deploy-snapshots"
        # When push to master occurs, all the versions should be -SNAPSHOTs and we will auto-deploy
        - mvn -Dmaven.wagon.http.retryHandler.count=3 --batch-mode -e -DskipTests=true deploy
    - stage: release-check
      script:
        - echo "release-check"
        # Ensure we don't have any external SNAPSHOT dependencies
        - mvn -Dmaven.wagon.http.retryHandler.count=3 --batch-mode release:prepare -DskipTests -Darguments=-DskipTests -DdryRun=true
    - stage: release
      script:
        - echo "release"
        # Git fix based on: https://github.com/sbt/sbt-release/issues/210
        - echo "Fixing git setup for $TRAVIS_BRANCH in preparation for release"
        - git checkout ${TRAVIS_BRANCH}
        - git branch -u origin/${TRAVIS_BRANCH}
        - git config branch.${TRAVIS_BRANCH}.remote origin
        - git config branch.${TRAVIS_BRANCH}.merge refs/heads/${TRAVIS_BRANCH}
        # Prepare for signing artifacts as part of release process
        # NOTE: based on http://www.debonair.io/post/maven-cd/ "Encrypt cert and variables for travis"
        - openssl aes-256-cbc -K $encrypted_4d75e2900770_key -iv $encrypted_4d75e2900770_iv -in travis/codesigning.asc.enc -out travis/codesigning.asc -d
        - gpg --fast-import travis/codesigning.asc
        # Perform mvn release steps
        - mvn -Dmaven.wagon.http.retryHandler.count=3 --batch-mode release:prepare -DskipTests -Darguments=-DskipTests -DtagNameFormat="v@{project.version}" -DscmCommentPrefix="[maven-release-plugin][skip travis]" # NOTE: this stop's travis from building based on the tag's commit/push.
        - mvn -Dmaven.wagon.http.retryHandler.count=3 --batch-mode release:perform -DskipTests -Darguments=-DskipTests
