name: vertx-base

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Cron job to run daily at midnight (UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: 'som-rit-infrastructure-prod'
        workload_identity_provider: 'projects/294515190965/locations/global/workloadIdentityPools/github/providers/susom-github'

    - name: Configure Maven to use gcloud as a credential helper
      run: |
        gcloud auth application-default login --quiet flag
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Copy Maven settings
      run: cp ./travis/maven-settings.xml $HOME/.m2/settings.xml

    - name: Update version in pom.xml
      run: sed -i "s/-SNAPSHOT/-build-${{ github.run_number }}/" pom.xml

  #  - name: Set up SonarCloud
  #    uses: sonarsource/sonarcloud-github-action@v2
  #    with:
  #      sonarToken: ${{ secrets.SONAR_TOKEN }}
  #      args: "-Pcoverage verify sonar:sonar -Dsonar.projectKey=susom_vertx-base"

    - name: After failure - Display Surefire reports
      if: failure()
      run: |
        echo "\n=== SUREFIRE REPORTS ===\n"
        for F in target/surefire-reports/*.txt; do echo $F; cat $F; echo; done

  deploy_snapshots:
    if: github.ref == 'refs/heads/master'
    name: Deploy Snapshots
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Deploy to Maven Central
        run: mvn -Dmaven.wagon.http.retryHandler.count=3 --batch-mode -e -DskipTests=true deploy