name: vertx-base

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Cron job to run daily at midnight (UTC)

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: 'som-rit-infrastructure-dev'
        workload_identity_provider: 'projects/333682183013/locations/global/workloadIdentityPools/github/providers/github-provider'
    
    - name: Configure Artifact Registry authentication
      run: |
        gcloud auth configure-docker us-west1-maven.pkg.dev
        gcloud config set artifacts/location us-west1
        gcloud config set artifacts/repository public-maven

      
    - name: Clear Maven cache
      run: rm -rf ~/.m2/repository

    - name: Copy Maven settings
      run: cp ./travis/settings.xml $HOME/.m2/settings.xml

    - name: Update version in test-pom.xml
      run: sed -i "s/-SNAPSHOT/-build-${{ github.run_number }}/" test-pom.xml

    - name: Display Surefire reports on failure
      if: failure()
      run: |
        echo -e "\n=== SUREFIRE REPORTS ===\n"
        if compgen -G "target/surefire-reports/*.txt" > /dev/null; then
          for F in target/surefire-reports/*.txt; do
            echo $F
            cat $F
            echo
          done
        else
          echo "No Surefire reports found."
        fi

  deploy_snapshots:
    if: github.event_name == 'push'
    name: Deploy Snapshots
    runs-on: ubuntu-latest
    environment: Deploy to Artifact Registry 
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: 'som-rit-infrastructure-dev'
        workload_identity_provider: 'projects/333682183013/locations/global/workloadIdentityPools/github/providers/github-provider'

    - name: Configure Artifact Registry authentication
      run: |
        gcloud auth configure-docker us-west1-maven.pkg.dev
        gcloud config set artifacts/location us-west1
        gcloud config set artifacts/repository public-maven

    - name: Clear Maven cache
      run: rm -rf ~/.m2/repository

    - name: Deploy Snapshots
      run: |
        mvn -f test-pom.xml -Dmaven.wagon.http.retryHandler.count=3 --batch-mode -e -DskipTests=true deploy -X
