name: vertx-base

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: 'read'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Set up Maven settings
        run: cp ./travis/new-settings.xml ~/.m2/settings.xml

      - name: Authenticate using Artifact Registry Key
        run: |
          echo "${{ secrets.ARTIFACT_REGISTRY_KEY }}" | base64 -d > $HOME/gcp_key.json
          gcloud auth activate-service-account --key-file=$HOME/gcp_key.json
          gcloud auth application-default login --key-file=$HOME/gcp_key.json

      - name: Build and test with Maven
        run: mvn -e -Pcoverage verify
        env:
          ARTIFACT_REGISTRY_KEY: ${{ secrets.ARTIFACT_REGISTRY_KEY }}

      - name: Show Surefire test reports on failure
        if: failure()
        run: |
          for F in target/surefire-reports/*.txt; do echo $F; cat $F; echo; done

  deploy-snapshots:
    name: Deploy Snapshots
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Set up Maven settings
        run: cp ./travis/new-settings.xml ~/.m2/settings.xml

      - name: Authenticate using Artifact Registry Key
        run: |
          echo "${{ secrets.ARTIFACT_REGISTRY_KEY }}" | base64 -d > $HOME/gcp_key.json
          gcloud auth activate-service-account --key-file=$HOME/gcp_key.json
          gcloud auth application-default login --key-file=$HOME/gcp_key.json

      - name: Update version in pom.xml
        run: |
          if [[ ${{ github.ref }} == "refs/heads/master" ]]; then
            sed -i 's/3.1-SNAPSHOT/3.1/' pom.xml
          else
            sed -i 's/3.1-SNAPSHOT/3.1-${{ github.run_number }}-SNAPSHOT/' pom.xml
          fi

      - name: Deploy Snapshots
        run: |
          mvn -Dmaven.wagon.http.retryHandler.count=5 \
              -Dmaven.wagon.httpconnectionManager.ttlSeconds=30 \
              -Dmaven.wagon.http.timeout=1200000 \
              --batch-mode -e -DskipTests=true deploy -X
        env:
          ARTIFACT_REGISTRY_KEY: ${{ secrets.ARTIFACT_REGISTRY_KEY }}