name: vertx-base

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Cron job to run daily at midnight (UTC)

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: 'som-rit-infrastructure-prod'
        workload_identity_provider: 'projects/294515190965/locations/global/workloadIdentityPools/github/providers/susom-github'

    - name: Copy Maven settings
      run: cp ./travis/settings.xml $HOME/.m2/settings.xml
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Update version in pom.xml
      run: sed -i "s/-SNAPSHOT/-build-${{ github.run_number }}/" pom.xml

    - name: Display Surefire reports on failure
      if: failure()
      run: |
        echo "\n=== SUREFIRE REPORTS ===\n"
        for F in target/surefire-reports/*.txt; do echo $F; cat $F; echo; done

  deploy_snapshots:
    if: github.event_name == 'push'
    name: Deploy Snapshots
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: 'som-rit-infrastructure-prod'
        workload_identity_provider: 'projects/294515190965/locations/global/workloadIdentityPools/github/providers/susom-github'
    
    - name: Copy Maven settings
      run: cp ./travis/settings.xml $HOME/.m2/settings.xml

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Deploy Snapshots
      run: |
        mvn -U clean install
        mvn -Dmaven.wagon.http.retryHandler.count=3 --batch-mode -e -DskipTests=true deploy -X
