name: vertx-base

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Copy Maven settings
        run: cp ./travis/actions-maven-settings.xml $HOME/.m2/settings.xml

      - name: Update POM Version
        run: sed -i "s/-SNAPSHOT/-github-build-${{ github.run_number }}/" pom.xml

      - name: Run Maven Tests
        run: mvn -e verify --settings $HOME/.m2/settings.xml

  # deploys into Artifact Registry when code is pushed to the master branch of the 'susom/vertx-base' repository.
  deploy_snapshots:
    name: Deploy Snapshots
    runs-on: ubuntu-20.04
    if: github.repository == 'susom/vertx-base' && github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: test
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.WORKLOAD_IDENTITY_PROJECT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: true

      - name: Set up OAuth2 access token for Maven
        run: |
          echo "ACCESS_TOKEN=$(gcloud auth print-access-token)" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Copy Maven settings for deploy
        run: cp ./travis/actions-maven-settings.xml $HOME/.m2/settings.xml

      - name: Update POM Version for deploy
        run: sed -i "s/-SNAPSHOT/-github-build-${{ github.run_number }}/" pom.xml

      - name: Deploy Snapshots
        run: mvn -s $HOME/.m2/settings.xml -Dmaven.wagon.http.retryHandler.count=3 --batch-mode -e -DskipTests=true deploy
